### ISSUE TITLE
Invalid asset group in multiasset token bundle - incorrect ordering of tokens

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#104]
Soon we will have hex encoded assets available on the cli, you can see a demo right here. However, hw-cli/app-cardano complains about an incorrect token ordering...

![image](https://user-images.githubusercontent.com/47434720/137603338-237903f0-25ec-4aeb-a0da-a05acfb137f5.png)

The TxBody itself is:
``` json
{
    "type": "TxBodyMary",
    "description": "",
    "cborHex": "83a5008182582012d6891bc839c7cea7ad3c034c32265db80c0420a29d3d9843687709fa14d99200018182581d6088ff402b0522f27649ac742238c697c579beeb344eb723099d1f16ce821b000000e43bdb642aa3581c2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15a440186d46112233221100181e464c614c654c75187b4568616c6c6f183c581c4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467a743000000181e430001000f45546573743114455465737432181e4554657374330f4554657374360a4a616c6f6e7a6f746573741907d0581c6b79ff1505414bd7ebba7a9b3242ba02810f0b91ea9e391c6e0b7409a1466877746573740a021a0002dcf1031a004ce7eb09a1581c6b79ff1505414bd7ebba7a9b3242ba02810f0b91ea9e391c6e0b7409a1466877746573740a9f8200581c8d87ba19c400938453e86abf8c2f1f9a94c1acf7f495978e70ab0068fff6"
}

```

Its possible to mint hex encoded assets on the ledger, tested it, thats working. But somehow in that example something results in an error. I thought the correct ordering was something we got rid of a while ago?

**Comment by gitmachtl** [comment]
Ah thx, that sounds good. Because i am not sure if cardano-cli will adapt to the "right" order. We had that discussion a while ago.

**Comment by gitmachtl** [comment]
@janmazak So, this sorting should be ok for hw-wallets? Or am i missing something here?

Unsorted:

``` json
[ 
  "6b79ff1505414bd7ebba7a9b3242ba02810f0b91ea9e391c6e0b7409.687774657374",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.112233221100",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.4c614c654c75",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.68616c6c6f",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.000000",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.000100",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737431",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737432",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737433",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737436",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.616c6f6e7a6f74657374"
]
```

Sorted:

``` json
[
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.68616c6c6f",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.112233221100",
  "2e2f143b3ccbe339145183dc2a799a469e92ab56e0d5b0bd04f54f15.4c614c654c75",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.000000",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.000100",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737431",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737432",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737433",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.5465737436",
  "4ef8525f365560af6b685169cac4c86acdd122d683d3400f6ca23467.616c6f6e7a6f74657374",
  "6b79ff1505414bd7ebba7a9b3242ba02810f0b91ea9e391c6e0b7409.687774657374"
]
```

**Comment by gitmachtl** [comment]
A solution to feed hw-cli with a txbody and get back the txbody with the right order would be the best option imo. So also for multi-signing transaction, you could normally generate the txbody with cardano-cli, feed it thru hw-cli and use the resulting txbody for further processing.

**Comment by gitmachtl** [comment]
when the updated libs are out in the wild, we will see many stuck funds on users that are using hw-wallets via the cli because of that ordering issue, so @KubqoA and @gabrielKerekes i am shy to ask, but how close are we currently to that added "txbody asses reordering" command we talked about earlier?

**Comment by KubqoA** [comment]
The library for the CIP-0021 compliance is currently being worked on, I am afraid I cannot tell you exactly when it will be finished, but we are doing our best to have it ready ASAP as we know it's quite a big blocker. If you need to follow the development, the library is being developed here: https://github.com/vacuumlabs/cardano-hw-interop-lib/pull/1

**Comment by gitmachtl** [comment]
> The library for the CIP-0021 compliance is currently being worked on, I am afraid I cannot tell you exactly when it will be finished, but we are doing our best to have it ready ASAP as we know it's quite a big blocker. If you need to follow the development, the library is being developed here: [vacuumlabs/cardano-hw-interop-lib#1](https://github.com/vacuumlabs/cardano-hw-interop-lib/pull/1)

thx, looks like you're making pretty fast progress on that front. thank you for your work!

**Comment by gitmachtl** [comment]
so this issue is getting urgent, i receive pictures like that:
![image](https://user-images.githubusercontent.com/47434720/142757366-02ba05f9-1abd-4d74-80cf-88b4b7acd503.png)

**Comment by janmazak** [comment]
Where does this come from? AFAIK neither Ledger nor Trezor released HW wallet updates that would enforce canonical ordering, and all SW wallets we know of have been updated (the last one was Daedalus on 18th Nov).

We are pretty close to finishing the hw-cli update, too, but we got stuck a bit on the non-standard internal serialization format of cardano-cli for raw transactions (to be signed) which does not conform to CDDL for full tx.

**Comment by gitmachtl** [comment]
> Where does this come from? AFAIK neither Ledger nor Trezor released HW wallet updates that would enforce canonical ordering, and all SW wallets we know of have been updated (the last one was Daedalus on 18th Nov).

a user sent this to me, he used yoroi and i asked three times about the cardano-app version and the reply was version 2.4.1

**Comment by gitmachtl** [comment]
i am closing this issue now, the asset ordering can now be resolved with the new added feature to sort a given tx in canonical order. 👍
