### ISSUE TITLE
program suddenly stopped working with 1.31.0

### ISSUE THREAD

**Issue by benapetr** [vacuumlabs/cardano-hw-cli#113]
I am getting these errors every single time I try to sign change to pool:

Version 1.6.2:
```
Error: Invalid file contents of tx-body-file
```

Version 1.9.0:
```
Error: Invalid raw transaction CBOR
```

tx-body-file is 100% valid CBOR, I tried decoding it using cardano-cli transaction view --tx-body-file tx-pool.raw it just shows a valid request to update pool. Is there any way to debug what specifically this program has issues with?

I don't remember changing anything, only thing that may have changed is the version of cardano-cli itself, I think we updated that to 1.31.0 but not sure if we even used different version last time when we signed. Ledger is still same version of firmware as well as cardano app.

**Comment by gitmachtl** [comment]
make sure to build the transaction as a --mary-era transaction. --alonzo-era transactions are not supported yet.

**Comment by benapetr** [comment]
yes that was the culprit, mary-era worked, this should be highlighted somehow somewhere :)

**Comment by gitmachtl** [comment]
there is already a issue report for that: https://github.com/vacuumlabs/cardano-hw-cli/issues/89 alonzo era support will be implemented soon...

**Comment by gitmachtl** [comment]
@davidmisiak @DavidTranDucVL issue can be closed i guess.
