### ISSUE TITLE
Avast antivirus complains on cardano-hw-cli-1.10.0

### ISSUE THREAD

**Issue by os11k** [vacuumlabs/cardano-hw-cli#125]
Hi,

Seems Avast antivirus complains on cardano-hw-cli-1.10.0:

![image](https://user-images.githubusercontent.com/6322576/174068956-5d772bf1-f16b-4090-ad76-672d2bd375c4.png)

I have no problem with 1.9.1

**Comment by os11k** [comment]
Sha256 of my downloaded file is `ef9260d97d56ac72b54d3ac6adb4c0e56bf782b5ef3b7f646c6bbfc4565e2d50`

What seems to be same as on the remote server

**Comment by os11k** [comment]
Downloaded file uploaded to virustotal.com online tool and this is what I get:

![image](https://user-images.githubusercontent.com/6322576/174076009-03853157-9a05-4895-ad3f-5da419f32cf6.png)

**Comment by davidmisiak** [comment]
Thank you for reporting this issue, we are investigating its causes and possible solutions. Similar issues [were reported](https://github.com/nexe/nexe/issues/945) to the Nexe project (also used by cardano-hw-cli) in the past, so it seems that they might be caused (at least partially) by the binary not being signed. We will let you know when we resolve the issue.

**Comment by gabrielKerekes** [comment]
👋 @os11k would you mind testing the current pre-release on Windows please? https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.11.0-rc.1I noticed your thumbs-up on the release, so please let us know if antivirus is ok with the `.exe` file now 🙏 Also if you happen to run any other tests on Windows, any feedback would be appreciated 🙇

**Comment by os11k** [comment]
Seems Avast doesn't complain anymore, but virustotal.com has 1 issue:

![image](https://user-images.githubusercontent.com/6322576/183902859-630cacfc-2647-41a1-9c65-38fd2e22a221.png)

**Comment by gabrielKerekes** [comment]
Interesting, I checked a couple of previous build with virustotal and they were ok. I'll take a look.

**Comment by gabrielKerekes** [comment]
Hm, I created [another pre-release](https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.11.0-rc.2) where I used Node.js v18 to build the binaries and apparently they are not flagged by any of the vendors 🤦 ([link to results](https://www.virustotal.com/gui/file/70fb5457d5457248a27d378f3322c8fd34c738e24e88a46aff286d9742cf3bed)) It seems a bit artificial to fix it this way and it's possible it'll start being flagged again at some point but at least for now, we should be good.

**Comment by os11k** [comment]
No issues with Avast with new build and virustotal.com is showing that everything is fine too:

![image](https://user-images.githubusercontent.com/6322576/184102706-c2ae144e-a19c-48a8-a7f2-a5af60a63976.png)

Nevertheless I got that screen in Windows 10, not sure how it is easy to fix it:

![image](https://user-images.githubusercontent.com/6322576/184102638-9ba4956e-cb57-4d1e-962f-949ff160aa8d.png)

**Comment by gabrielKerekes** [comment]
I think the windows defender warning can not be removed unless we sign the binaries which we currently don't plan on doing.

**Comment by davidmisiak** [comment]
Thanks everyone, so the Avast & Virustotal issue seems to be resolved (latest pre-release [here](https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.11.0-rc.4), a proper release coming soon). Should there be any other issue, let us know!
