### ISSUE TITLE
Add --version subcommand

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#13]
For a smoother debugging experience, to be able to track down the actual hw cli version where an unexpected error happened, it would be beneficial to reproduce the `--version` subcommand of `cardano-cli` (at least show the version, but the ideally the exact git commit as well):

```
$ cardano-cli --version
cardano-cli 1.19.1 - linux-x86_64 - ghc-8.6
git rev 497afd7dedc5d5b9bdcdb0e3cac6a50bd9f7dd54

```

**Comment by DavidTranDucVL** [comment]
Implemented in https://github.com/vacuumlabs/cardano-hw-cli/pull/11
