### ISSUE TITLE
FR - Add a flag to change the default derivation method for Trezor devices

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#131]
As stated in https://github.com/trezor/trezor-firmware/issues/1783 there are a number of different seed derivation schemes used in Cardano. But the 24 word seed implementation had a bug in Trezor. There was a fix for that, and the latest version is using Icarus. However the version with the Bug "Icarus_Legacy" is the default fallback method used in cardano-hw-cli. So if a Trezor device is used with 24 seed words, the derived keys/addresses via cardano-hw-cli don't line up anymore with the ones shown in Trezor-Suite right now. And using addresses generated via hw-cli results in "Cardano Legacy" addresses within Trezor-Suite.

Feature request is to add a flag that would tell cardano-hw-cli to use the newer "Icarus" method and not the "Icarus_Legacy" method.

@refi93 

![image](https://user-images.githubusercontent.com/47434720/184690620-d8fd3207-5de2-489c-889a-ca21f6fe1644.png)

**Comment by davidmisiak** [comment]
@janmazak I think we can control the derivation scheme by setting the `derivationType` parameter on Trezor Connect calls (docs e.g. [here](https://github.com/trezor/connect/blob/develop/docs/methods/cardanoSignTransaction.md)).

**Comment by gitmachtl** [comment]
@davidmisiak Side question: I see that [here](https://github.com/trezor/connect/blob/develop/docs/methods/cardanoSignTransaction.md#pool_registration_as_owner) are also entries for PoolRegistration. Since when is it possible to do a PoolRegistration via a Trezor HW-Wallet? That was only working on Ledger in the past.

**Comment by gitmachtl** [comment]
> @gitmachtl Well, cardano-hw-cli is a pass-through tool with respect to derivation paths and derived keys, it has no control whatsoever about how keys are derived in the connected HW device (ledger/trezor), and it never derives any keys on its own.

I am just wondering how Trezor-Suite can also show the "Ledger" part without knowing the root-key? is Tretor-Suite requesting this from the device in a silenced mode?

**Comment by davidmisiak** [comment]
> Hmm... i am using trezor-bridge on the cli, is this also available in bridge?

Yes, bridge only forwards commands generated by Trezor Connect.

**Comment by davidmisiak** [comment]
Feature added in https://github.com/vacuumlabs/cardano-hw-cli/pull/135
