### ISSUE TITLE
Can't generate Byron paths

### ISSUE THREAD

**Issue by gabrielKerekes** [vacuumlabs/cardano-hw-cli#134]
The following command fails with `Error: not implemented` because of [this line](https://github.com/vacuumlabs/cardano-hw-cli/blob/925878a2ed53c1e6acc6147b4ef6895f8cbba1fb/src/fileWriter.ts#L129).
```
cardano-hw-cli address key-gen \
--path 44H/1815H/0H/0/0 \
--verification-key-file byron.vkey \
--hw-signing-file byron.hwsfile
```

Byron keys should still be supported though. One suggestion for the key description is `Payment Verification Key`.

See https://github.com/vacuumlabs/cardano-hw-cli/issues/133#issuecomment-1233920435 for context.

**Comment by davidmisiak** [comment]
Fixed in https://github.com/vacuumlabs/cardano-hw-cli/pull/135
