### ISSUE TITLE
Remove legacy features

### ISSUE THREAD

**Issue by davidmisiak** [vacuumlabs/cardano-hw-cli#138]
As stated in [README.md](https://github.com/vacuumlabs/cardano-hw-cli/blob/d52a82c31831997d086a33e53d081b142f6afd89/README.md), support for the `sign` call and `--tx-body-file` input format should be dropped soon.

This requires  rewriting integration tests so that all of them use the `witness` call and the new CDDL-compliant tx format.

**Comment by gitmachtl** [comment]
Starting with cardano-node 1.35.4 and so also cardano-cli 1.35.4, there is no support anymore for the intermediate `--cli-format` tx-body. It is now all per default in `--cddl-format`. And thats the only option from now on.

**Comment by janmazak** [comment]
Done in https://github.com/vacuumlabs/cardano-hw-cli/pull/142, will be merged in https://github.com/vacuumlabs/cardano-hw-cli/pull/137 together with other things.
