### ISSUE TITLE
windows version appears to be infected according to antivirus

### ISSUE THREAD

**Issue by angelstakepool** [vacuumlabs/cardano-hw-cli#141]
When cardano-hw-cli zip file is downloaded on windows, my antivirus throws the following message:

"<path>\cardano-hw-cli-1.12.0_windows-x64.zip tried to load a malicious resource detected as Trojan.Agent.GBOR and was blocked."

**Comment by janmazak** [comment]
I've tried some tools to check the file and they don't report any threat. Not sure if we can do anything about it anyway, we are fully relying on the newest version of [pkg](https://www.npmjs.com/package/pkg) to create the executable. Soon, v1.13 will be ready, so you can try if the problem still persists. (I am attaching a win build corresponding to the newest branch at this moment, perhaps you can check it with your antivirus?)
[cardano-hw-cli-1.12.0_windows-x64.zip](https://github.com/vacuumlabs/cardano-hw-cli/files/10664800/cardano-hw-cli-1.12.0_windows-x64.zip)
