### ISSUE TITLE
No Issue but a question - More than one account on a ledger? Testnet-Addresses?

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#15]
Hi,

i made the scripts here to create adresses, create stakepools, etc...
https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet

many are using them, so i wanna update them to be compatible with your cardano-hw-cli too.

Question1) Is there a way to create more than one account on a ledger device? I think it is not possible right?
Question2) Is the cardano-hw-cli compatible with the current testnet and the testnet-address-format? Or only mainnet?
Question3) Is it possible to have more than one ledger device connected at the same time?

Thx! Best regards, Martin

**Comment by refi93** [comment]
Hi @gitmachtl

Answers:
1. with the currently launched Ledger app version (2.0.4) you should be able to derive account keys up to number `20'` if you mean accounts in the BIP44 sense, the upcoming app version should support accounts up to 100'
2. yes, signing testnet transactions is supported, you specify that with the `--testnet-magic <number>` parameter in the same way as in cardano-cli
3. no, device selection is not supported right now
