### ISSUE TITLE
Shows "use latest cardano app" error

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#16]
cardano-hw-cli release version 1.1.0

```
> sudo ./cardano-hw-cli shelley address key-gen --path 1852H/1815H/0H/0/0 --verification-key-file payment.vkey --hw-signing-file payment.hwsfile
Error: Operation not supported by the Ledger device, make sure to have the latest version of the Cardano app installed

Ledger Nano S:
> sudo ./cardano-hw-cli device version
Ledger app version 2.0.4

Ledger Nano X:
> sudo ./cardano-hw-cli device version
Ledger app version 2.0.5
```

**Comment by refi93** [comment]
Hi @gitmachtl - yes, we are aware of the bug, the cardano-hw-cli latest release has an outdated version of the ledger library that had backwards-compatiblity issues with Ledger, here is an open PR that fixes it

**Comment by gitmachtl** [comment]
Thanks!

**Comment by DavidTranDucVL** [comment]
Fixed in https://github.com/vacuumlabs/cardano-hw-cli/pull/14 and https://github.com/vacuumlabs/cardano-hw-cli/pull/11
