### ISSUE TITLE
How to use cardano-hw-cli to use existing payment/staking key in ledger instead of geenrating new ones ?

### ISSUE THREAD

**Issue by HuguesD** [vacuumlabs/cardano-hw-cli#161]
Hi,

As a stake pool owner, I'd like to use my existing nano ledger containing my existing Cardano payment/staking keys.
Is there a way to use these existing keys instead of generating new ones in this ledger device ? If so how to do that ?
the current cardano-hw-cli seems to only have a new "key-gen" option, but no option to use existing keys

Any help welcome
Thanks

**Comment by gitmachtl** [comment]
Hi,

take a look at the StakePool Operator Scripts here: https://github.com/gitmachtl/scripts

Its a suite of little scripts with full HW-Wallet Support which is using cardano-hw-cli. You can easily generate the Keys from your Ledger. Simply run the script 03a. You can optionally specify an account number to derive the key from, if you have used multiple ones in the past.

Best regards,
 Martin

**Comment by HuguesD** [comment]
Hi,

thanks for answering. However I'm not sure I expressed clearly what I'm looking for. 
Indeed, if I'm not wrong, script 03a will generate new keys in a ledger.
What I'd like is to not create new keys in a ledger but to use the existing key pairs of my Cardano account for which the keys were already generated in the ledger (these key paris payment and staking were generated by the Cardano app running on the ledger when I created my account).

I understand vaguely, but not clear to me, that I could still use your scripts AND reuse my existing ledger key pairs ?
Also another thing that is not clear at all, is if the Cardano app needs to be run on the ledger when running the scripts ?

thanks in advance for your help
Hugues

**Comment by gitmachtl** [comment]
@HuguesD ok, looks like you don't know how the hw-wallet actually works. in short, you have your seed phrase that you get on the first startup, or that you can enter. the hw-wallet internally generates a root key out of this seed phrase. all the different cryptos on your hw wallet use the same root key, but they use different derivation paths. for cardano the derivation paths are `1852H/1815H/0H/0/0` for the payment-key and `1852H/1815H/0H/2/0` for the staking-key. 

you can't create new keys on the hw wallet, they are always already all there. you just can grab them from the hw wallet. so you will get the publickey(vkey) and a reference to the secretkey(hwsfile) out of it. and as long as you don't change the seed phrase, they will always be the same no matter what.

so if you run for example:
`./03a_genStakingPaymentAddr.sh hugues hw`
that would pull the payment(base-address) and staking key from the hw wallet and creates files like
`hugues.payment.vkey, hugues.payment.hwsfile, hugues.payment.addr, hugues.staking.vkey, hugues.staking.hwsfiles, hugues.staking.addr`
for you.

you do so by interacting with the cardano-app on the hw wallet (ledger or trezor) yes, so this must be installed and opened.

hope this makes it a bit clearer for you?

best regards, martin

**Comment by HuguesD** [comment]
Ok, so I understand that this does what i expected. The 03 key-gen script will not erase existing key pairs nor create new ones within the ledger hw. It will refer to the existing "account" via the public vkeys and links to the secret keys (that never does get out of the hw obviously). 
So when the script is named as "generating key payment & staking key pairs", it means in fact creating the vkey, hws and addr files based on what exists within the ledger usb stick. Right ?

**Comment by gitmachtl** [comment]
@HuguesD in short, yes 😄

**Comment by HuguesD** [comment]
Great, then we can conclude the issue os solved! Thanks a lot for your explanations and support (of a noob)

**Comment by merlinana** [comment]
@HuguesD Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by HuguesD** [comment]
> @HuguesD Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.
> 
> Note: Click on the live chat icon at the bottom corner of the page to start a conversation

Beware, this answer is from a spammer obviously as this same answer comes on all of my github posts, whatever the topic is.

**Comment by gitmachtl** [comment]
@refi93 @gabrielKerekes can you please remove the SPAM post an close the topic, thx.

**Comment by gabrielKerekes** [comment]
@gitmachtl thanks for responding and for bringing the phising attempt to our attention :pray: Comment reported (FWIW) and deleted.
