### ISSUE TITLE
Not possible to sign valid Catalyst registrations with Ledger app 5.x.x

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#165]
As can be seen in the announcement of the ongoing Fund10: https://iohk.zendesk.com/hc/en-us/articles/900006490763-Project-Catalyst-FAQ Catalyst voting round requires as a reward destination a payment address instead of a stake address and Ledger app v6.x.x hasn't been released yet. Ledger app v5.x.x doesn't work with the latest CLI for signing catalyst registrations as a switch from cip-15 to cip-36 format was made.

While Ledger app v 5.x.x which works with hw cli 1.12 can technically sign CIP-15 Catalyst registrations with a payment address as the destination, this seems not possible with the CLI as it enforces stake addresses: https://github.com/vacuumlabs/cardano-hw-cli/pull/151/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L90

Proposed solution: at least temporarily allow making CIP-15 registrations with hw cli, or at least make a patched version of hw cli 1.12 to not lock out cli users from the ongoing Fund10 Catalyst

**Comment by gitmachtl** [comment]
Thanks for opening up that issue, as we talked about it earlier. If a fast solution can be made, it may be worth to compile a hw-cli version 1.12.1 or so for that? As 1.13 already moved on with the code to cip-36.

**Comment by gitmachtl** [comment]
@refi93 @janmazak please give an update as soon as possible if a "intermediate" hw-cli 1.12.1 will be available. of if we roll with 1.12 and stake-addresses. its important to get the documentation and changed tooling out also as soon as possible. thx guys!

**Comment by gitmachtl** [comment]
@refi93 @janmazak i did some testing and cardano-hw-cli 1.12 works with a payment address for the rewards address already! 😄 

had to modify my scripts back to the old parameters, also the payment address must be on the hw-wallet itself again of course.

but it works with cardano-app 5.0.1

so i think we can simply guide the people to use cardano-hw-cli 1.12 for catalyst registration?

![image](https://github.com/vacuumlabs/cardano-hw-cli/assets/47434720/36aaa87e-f516-4ba4-bc77-006f90c47824)

**Comment by gitmachtl** [comment]
Documentation updated:
https://github.com/gitmachtl/scripts/blob/master/Catalyst_Registration_CLI_Tools.md

**Comment by refi93** [comment]
Thanks @gitmachtl for checking it, closing the issue
