### ISSUE TITLE
Error: Extended public key export cancelled by user

### ISSUE THREAD

**Issue by SebastienGllmt** [vacuumlabs/cardano-hw-cli#166]
I'm trying to run the following command on my Trezor device on the latest version of cardano-hw-cli and latest Trezor firmware

```bash
cardano-hw-cli node key-gen \
 --path 1853H/1815H/0H/0H \
--hw-signing-file ./cold.hwsfile \
--cold-verification-key-file ./cold.vkey \
--operational-certificate-issue-counter-file ./cold.counter
```

The device then prompts me to enter my Trezor passphrase, but after I enter it and accept I get `Error: Extended public key export cancelled by user` which seems to come from [this code](https://github.com/search?q=repo%3Avacuumlabs%2Fcardano-hw-cli%20TrezorXPubKeyCancelled%20&type=code)

Any idea what the issue could be? Cardano-hw-cli swallows the original error message, so it's hard for me to know what is going wrong

**Comment by davidmisiak** [comment]
Hi, I think this is caused by the fact that Trezor doesn't support 1853' path derivation (as well as signing pool registration transactions as operator), as noted [here](https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/pool-registration.md#create-pool-keys).
