### ISSUE TITLE
can not sign as operator witness

### ISSUE THREAD

**Issue by ThaiTheo** [vacuumlabs/cardano-hw-cli#17]
In the poolRegistration.md within docs you can not use cardano-hw-cli to sign as an operator witness.

![image](https://user-images.githubusercontent.com/41171413/102457126-85b23500-4042-11eb-9a15-7f1f1f8d814d.png)

This would be necessary if you want to keep all payments within 1 ledger (operator witness and owner witness both signed with hardware).

In the delegation-example.md within docs you can create a payment.addr and actually use cardano-hw-cli to sign transactions that you want to do with it.

**Comment by refi93** [comment]
Hi @ThaiTheo - the Ledger/Trezor upcoming releases (Ledger Cardano app 2.1.0 and Trezor fw 2.3.5) which will have stake pool registration certificate support will support only signing with the owner's staking key (due to security reasons, as explained e.g. in Trezor-connect docs: https://github.com/trezor/connect/pull/695/files), so the transaction inputs to pay the fees/deposit have to be signed via the standard cardano-cli, as can be seen in hw-cli's docs: https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md#sign-the-transaction

**Comment by avilsmeier** [comment]
Hi @refi93, any idea when ledger app 2.1.0 might be released?
Thanks!

**Comment by psychomb** [comment]
Hello, 
Do you know if support will come for witnessing a tx, not for a single owner, but for a reward account as well. One advantage of a hw is too make safe and repeated transactions. The reward wallet in that sense is supposedly much more active than an owner wallet.
Many thanks,

**Comment by refi93** [comment]
@avilsmeier tentative ETA by Ledger devs is before December 24

@psychomb in case of stake pool registration certificates, you don't need to provide a witness for the reward account where the owners' rewards are collected, you just provide the reward account address. If you mean performing withdrawals from the reward account, that's already supported. An example explicitly referencing withdrawals is missing from the hw-cli docs, but you just need to assemble the raw transaction with the withdrawal in the standard cardano-cli (supplying the reward address vkey) and have the raw transaction signed by the hw-wallet cli, supplying the reward address he signing key

**Comment by psychomb** [comment]
Thanks for your answer. I really was certain that the reward account needed to sign the pool cert as well. My bad. 
One pain point is the ability to have multiple owners in the pool. This is particularly important for switching from cli keys to hw-cli keys, as there must be some overlap if one wants to honor the pledge during address switching. Do you know if that will become possible ? Atm, my trials all failed.
Thanks,

**Comment by refi93** [comment]
@psychomb - when you have multiple owners, each one can provide their separate signature as described here: https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md#sign-the-transaction and then you join the tx body and signatures with the sign-witness command, as described in the [next section](https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md#create-signed-transaction) When providing the individual witnesses, each party may or may not use the hw-cli as can be seen in the example I referenced.

Did you try it that way? If so, and you are still stuck, can you describe your approach, ideally with the commands you used, so we can replicate/analyze it?

**Comment by angelstakepool** [comment]
I am looking forward to 2.1.0 release to be able to support 2 owner accounts (CLI and HW keys), so that we can have a smooth transition of pledge and no gaps in between. This is paramount for large pools that cannot just switch to a single HW owner key

In case it may be of help, when trying to create a witness with HW stake key, I would get as error

_**Error: Operation not supported by the Ledger device, make sure to have the latest version of the Cardano app installed"**_

Thanks,

**Comment by psychomb** [comment]
@refi93 Thanks for your reply. 
Basically I get the error mentioned by @angelstakepool. 

Let's say I create a pool registration certificate like so
````
 cardano-cli stake-pool registration-certificate \
--cold-verification-key-file ./secrets/stkht.vkey \
--vrf-verification-key-file ./secrets/vrf.vkey \
--pool-pledge 100000000 \
--pool-cost 500000000 \
--pool-margin 0.075 \
--pool-reward-account-verification-key-file ./purse_wallet/purse_stake.vkey \
--pool-owner-stake-verification-key-file ./owner_cli/owner_cli_stake.vkey \
--pool-owner-stake-verification-key-file ./owner_hw/owner_hw_stake.vkey \
--pool-relay-ipv4 100.100.100.100 \
--pool-relay-port 6666 \
--metadata-url https://stakhanovite.io/cardano/stkh_testnet.json \
--metadata-hash $(cat ./secrets/stkht_metadata) \
--mainnet \
--out-file poolregtest
````
I continue by building a transaction - the one paying is irrelevant here, but let's say I make use of the reward address (here my purse wallet) - and it includes the `--certificate-file poolregtest`. 

When I try to witness like so 
````
cardano-hw-cli shelley transaction witness --tx-body-file ./tx.raw --hw-signing-file ./owner_hw/owner_hw_stake.hwsfile --out-file witness_owner_hw
````
The output is : 
`Error: Operation not supported by the Ledger device, make sure to have the latest version of the Cardano app installed
`
Whereas witnessing for the two other is perfectly fine :
`cardano-cli transaction witness --tx-body-file ./tx.raw --signing-key-file ./secrets/stkht.skey  --out-file witness_pool` 
and 
`cardano-cli transaction witness --tx-body-file ./tx.raw --signing-key-file ./owner_cli/owner_cli_stake.skey  --out-file witness_owner_cli`

It seems that a pool registration with more than one owner is not accepted. At least, some discussions on Telegram point in that direction, and that a firmware update for Ledger would solve this issue.

I hope this helps. 
Cheers,

**Comment by refi93** [comment]
That error is related to not having Ledger app 2.1.0 installed (which was not released yet, as pointed out in my previous comment), which is the version that adds the support for stake pool owner registration for hw-wallet backed owners. Unfortunately, the release of the app got recently postponed to January (exact release date TBD, probably first half of the month).

If you want to try the functionality earlier, you can build it from the ledger's app source (If you have a Ledger Nano S, SDK for Nano X is not public): https://github.com/LedgerHQ/app-cardano - however, such app won't be signed, so it's good only for experimenting with testnet and/or a seed that is not linked to a wallet with critical funds (not even of another coin). Here are the instructions to build Ledger apps from source and load them into Ledger, if you are interested: https://ledger.readthedocs.io/en/latest/userspace/getting_started.html

**Comment by gitmachtl** [comment]
I tried to load the app 2.1.0 on one of my Nano S devices, but the make load command fails at this stage:

**Comment by gitmachtl** [comment]
I got the 2.1.0 installed on one of my Nano S devices, will continue to check... thx!

**Comment by refi93** [comment]
Hw wallets were developed for Shelley era and they don't support changes introduced in Mary/Allegra era yet. So changing the tx type would work only for tx bodies that actually don't differ across eras.

Aren't you able to build the transaction for shelley-era (which based on the changelog should still be the default: https://github.com/input-output-hk/cardano-node/releases - 1.24.2 "CLI changes")? If you depend on some Mary/Allegra-specific feature(s), those are unfortunately not supported yet by the hw wallets.

**Comment by refi93** [comment]
@gitmachtl sorry for the delayed response - see my response to the related Mary/Allegra era issue: https://github.com/vacuumlabs/cardano-hw-cli/issues/31 - let's continue there

closing this as the original issue has been resolved by pointing to the correct version of the Ledger Cardano app
