### ISSUE TITLE
Conway Era - New StakeAddress Registration/Retirement Certificate Support

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#170]
@refi93 

Hi,

so, beside the new stuff like dRep-Key generation/signing and CCM-Cold/Hot-Key generation/signing on the HW-Wallet, there are also changes to existing certificates. 

## Stake-Address Registration- & Retirement Certificate Changes

* So pre Conway-Era, the transaction containing the StakeAddress-Registration Certificate did not need a witness from the StakeKey itself. Everybody could register even somebody elses StakeAddress. This is not gone starting with Conway-Era and the new certificate.
HW-Wallets had forever the restriction that you have to pay with it for the own StakeAddress registration. This restriction could maybe lifted, because now we also need a Witness from the StakeKey itself for the transaction. So we need a Witness from the StakeKey itself from now on for a StakeAddress registration. This change could be implemented right now also for pre Conway-Era transactions, because it does not hurt if there is an extra witness in the transaction.

* In addition to that, the new certificate also contains now the current deposit value. In the past this value was always fixed to 2000000 lovelaces (2 Ada) for a StakeAddress registration. Starting with Conway-Era this deposit value can be changed via actions. The new certificate now contains the used deposit value, because we need the same deposit value to be refunded when we retire the StakeAddress. So the new certificates have an additional field in it representing the deposit amount. This deposit amount should also be displayed on the HW GUI during the signing process.

Here is a link to the new cddl specs for these two certificates:
https://github.com/input-output-hk/cardano-ledger/blob/bcf6051f4a0b69c82e4de7327d7d8801fa1bad87/eras/conway/impl/cddl-files/conway.cddl#L303-L304

This is a typical StakeAddress Registration Certificate Pre-Conway:
```js
[
    0,
    [
        0,
        h'96e1844b60ec3bbe4a61b0bfdc2ca8f490f75e743bf5ebf8683ae6b8',
    ],
]
```

And this is the new format starting in Conway-Era with the additional deposit amount field:
```js
[
    7,
    [
        0,
        h'c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73f',
    ],
    2000000_2,
]
```

The deregistration certificate is similar, just with index value 8.

There are also a few other new certificates for Conway-Era like Registration+Delegation at the same time, but i don't think they have to be implemented in cardano-hw-cli beside the dRep and Constitutional Commitee Member stuff. Because such transaction can be also done separate.

Thx, Martin

**Comment by janmazak** [comment]
We will add witnesses for both the new Conway stake registration certificate and the legacy pre-Conway one. As for the other certificates, they will be supported to the extent Ledger and Trezor will support them.

We aim to finish hw-cli update in December 2023, but some things have still not been settled (e.g. anchor URL length change is pending).
