### ISSUE TITLE
Operational certificate signing not supported by Ledger app version 7.1.2

### ISSUE THREAD

**Issue by slux83** [vacuumlabs/cardano-hw-cli#178]
Hi,

I was trying to rotate my pool KES keys, but I got the following error (using the latest release of the `cardano-hw-cli` 1.14.0).

This is what I get when I try to use the `issue-op-cert` option from the utility
```
Error: The requested operation failed. Check that your Ledger device is connected, unlocked and with Cardano app running.
Details: DeviceVersionUnsupported: Operational certificate signing not supported by Ledger app version 7.1.2.
```
Any help? Thank you!

**Comment by bradstevens1** [comment]
Hello @slux83 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by slux83** [comment]
Scammers? LOL

**Comment by bradstevens1** [comment]
Not a scammer just trying to help you

**Comment by slux83** [comment]
Alright, version v1.16.0-rc.1 seems to work fine!

**Comment by janmazak** [comment]
The 1.16 version of hw-cli, although OK to use, cannot be made official because it contains a trezor-connect fork with code that has not been reviewed by trezor yet (related to message signing). No ETA, the PR has been stuck at Trezor for months.
