### ISSUE TITLE
Add more detailed docs

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#19]
The current pool registration demo is just a sequence of instructions: https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md - a new user would likely not be able to understand from it how to register astake pool properly and what are the limitations (only pool owners can provide their signatures from hw wallets) It would be great to add some paragraphs describing in detail what's going on and references to standard cli docs.

**Comment by xdzurman** [comment]
Solved by https://github.com/vacuumlabs/cardano-hw-cli/commit/83fcb051921a18167353b720d55fb3e730a146ee
