### ISSUE TITLE
Stop enforcing "shelley" prefix in cli commands

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#21]
cardano-cli was updated in December 2020 to no longer require including the "shelley" subinstruction for every shelley-era instruction, as can be seen in the change log: https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/ChangeLog.md#1240----december-2020

Actionables:
* do not require the "shelley" infix as well (but probably good idea to keep it optional to retain consistency with cardano-cli so users are not confused
* update docs to not include the "shelley" subinstruction in cardano-cli and hw-cli instructions

**Comment by DavidTranDucVL** [comment]
Resolved in https://github.com/vacuumlabs/cardano-hw-cli/pull/35
