### ISSUE TITLE
cannot create witness for maryTX.raw assetMinting transaction

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#24]
```
cardano-hw-cli shelley transaction witness --testnet-magic 3 --tx-body-file /tmp/ledger1.payment.txbody --hw-signing-file ledger1.payment.hwsfile --out-file /dev/stdout
Error: Failed to parse output
```

I tried to create a witness for a maryTX transaction for asset minting on a ledger nano x. Is this a cardano-hw-cli bug or also related to the ledger fw?

**Comment by refi93** [comment]
Hi @gitmachtl - asset mining is not yet supported by hardware wallets, therefore it isn't supported by the cardano-hw-cli either. But I agree the error you see could be more comprehensive in that regard and instead an "invalid argument" error should be displayed for which I created a dedicated issue: https://github.com/vacuumlabs/cardano-hw-cli/issues/26
