### ISSUE TITLE
using /dev/stdout as a standard pipe for --out-file is not working

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#25]
`cardano-hw-cli shelley transaction sign --testnet-magic 3 --tx-body-file /tmp/ledger1.payment.txbody --hw-signing-file ledger1.payment.hwsfile --hw-signing-file ledger1.staking.hwsfile --out-file /dev/stdout
`

results in: `Error: ESPIPE: invalid seek, write`

using a normal file as destination is working. but this is a standard linux pipe thing, why is this not working with cardano-hw-cli?

**Comment by gitmachtl** [comment]
is it possible that we can use /dev/stdout as an output filename? thats standard linux bash style, i am not quite sure why it is not working right out of the box.

**Comment by refi93** [comment]
this seems to be a bug that in cardano-hw-cli's file handling logic, probably the library we are using simply does not work properly with device files which we didn't account for when developing/testing it - we'll investigate it when we get back from holidays (after Jan 6th)

**Comment by DavidTranDucVL** [comment]
Resolved in https://github.com/vacuumlabs/cardano-hw-cli/pull/34
