### ISSUE TITLE
Showing "failed to parse output" for invalid arguments

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#26]
Currently the hw wallet cli is showing "Error: Failed to parse output" for an invalid argument as pointed out in https://github.com/vacuumlabs/cardano-hw-cli/issues/24

Expected behavior (inspired by cardano-cli):

```
$ cardano-cli adfdsf
Invalid argument `adfdsf'

Usage: cardano-cli (Byron specific commands | Shelley specific commands | 
                     Miscellaneous commands)

```

for other subcommand it should be showing the respective manual for commands - the most sensible is probably to use cardano-cli as a reference

**Comment by DavidTranDucVL** [comment]
```
yarn dev adfdsf
```
currently returns
```
usage: cardano-hw-cli [-h] {version,device,address,key,transaction} ...
cardano-hw-cli: error: invalid choice: 'adfdsf' (choose from 'version', 'device', 'address', 'key', 'transaction')
```
The error in question: `Error: Failed to parse output` is thrown during transaction parsing - it encountered invalid field in transaction body. Command in https://github.com/vacuumlabs/cardano-hw-cli/issues/24 was called with valid arguments.
