### ISSUE TITLE
poolRegistration payment via ledger is not supported

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#28]
looks like it is not possible to create a payment witness for a pool registration with ledger:
`Error: Unexpected payment hardware signing file with pool registration certificate found`

please correct that, thx

**Comment by refi93** [comment]
@gitmachtl currenly only stake pool registration from stake pool owners' perspective is supported by hw wallets.

Paying for the stake pool registration transaction is not allowed form the hw wallet (when signing as an owner) for security reasons, so it cannot by bypassed at cardano-hw-cli level either.

The problem (as outlined in hw wallet js lib docs: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/pool-registration-docs/docs/certificates.md#stake-pool-registration-as-an-owner-limitations) is that if we allowed to the owners providing witnesses for inputs, that would need to be optional (it's as legitimate for an owner to fund the pool registration transaction as not to) and it would be possible for a malicious operator to trick the pool owners into funding their pool registration transaction even if they want to, or even getting hold of their funds by providing an output address they own. So a practical design decision was made to just completely remove that option from the owners when signing the transaction from a hw wallet to not expose their funds to any risk.
