### ISSUE TITLE
.deb package compiled for i386 machines?

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#30]
Why is the .deb package compiled for i386 and not amd64 machines? I can an error trying to install it this way, or am i doing something wrong here? Extracting the .tar file and using it that way is no problem, but i also tried your dpkg -i .deb-package method and that showed an i386 error.

**Comment by refi93** [comment]
@gitmachtl - that's interesting, what .deb package are you trying? It installs and runs fine on my amd64 Ubuntu 20.04:

```
$ sudo dpkg -i cardano-hw-cli_1.1.1-1.deb 
Selecting previously unselected package cardano-hw-cli:i386.
(Reading database ... 304770 files and directories currently installed.)
Preparing to unpack cardano-hw-cli_1.1.1-1.deb ...
Unpacking cardano-hw-cli:i386 (1.1.1-1) ...
Setting up cardano-hw-cli:i386 (1.1.1-1) ...
$ Downloads lsb_release -a                         
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ Downloads uname -m
x86_64
```

This is the release from which I got the .deb file I installed: https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.1.1

**Comment by gitmachtl** [comment]
```
$ sudo dpkg -i cardano-hw-cli_1.1.1-1.deb
dpkg: Fehler beim Bearbeiten des Archivs cardano-hw-cli_1.1.1-1.deb (--install):
 Paket-Architektur (i386) passt nicht zum System (amd64)
Fehler traten auf beim Bearbeiten von:
 cardano-hw-cli_1.1.1-1.deb

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ uname -a
Linux DebianPrivate 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**Comment by refi93** [comment]
seems like you don't have i386 support enabled, running
```
sudo dpkg --add-architecture i386
sudo apt-get update
``` 
should solve the problem. Does that work for you?

Resources:
https://wiki.debian.org/Multiarch/HOWTO 
https://www.howtoforge.com/multiarch-how-to-use-32bit-packages-on-a-64bit-system-debian-7-wheezy

**Comment by gitmachtl** [comment]
I will try that thx, i am pretty sure i386 support is not enabled on my system yet.

**Comment by gitmachtl** [comment]
Yes it worked, tried it on a fresh Test-VM. You need to install the i386 architecture support first.
