### ISSUE TITLE
Show prompt on Trezor when exporting public key

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#36]
Motivation: Currently when exporting the public key on Trezor it happens "silently" so the user doesn't really get a feedback when they export the key which may confuse them if the key was actually exported.

Solution: trigger prompt on device when exporting the public key (same as Ledger already does). AFAIK there should be an option to enable on-device prompt

**Comment by DavidTranDucVL** [comment]
This issue was resolved
