### ISSUE TITLE
Incorrect witness type

### ISSUE THREAD

**Issue by PeterBenc** [vacuumlabs/cardano-hw-cli#45]
`Expected one of: TxWitnessByron, TxWitnessShelley, TxWitness AllegraEra, TxWitness MaryEra Actual: TxWitnessAllegra`

**Comment by gitmachtl** [comment]
I have the same issue with 1.1.2 on a mary chain:

**Comment by PeterBenc** [comment]
Hi, sorry for the inconvenience, hotfix is to manually fix the type of witness in the witness file. Either way, hw wallets do not yet support Alegra and Mary's transactions.

**Comment by gitmachtl** [comment]
its not with witness files, its with direct transactions too.

**Comment by PeterBenc** [comment]
You are right, it also an issue with the direct txs, :+1: . Afaik Allegra transactions can have the TTL field empty, which is not supported by the HW wallets. It's optional so if you included it in the tx you had no problems. In that case, the only issue should be the type of the output file. We ll fix it so it returns the right type of file.

**Comment by DavidTranDucVL** [comment]
Envelope type fixed in https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.1.3 . `validity interval start` and `multi-asset` is not supported yet, we are working on adding these features.

**Comment by gitmachtl** [comment]
Thx it is working now again in 1.1.3

**Comment by PeterBenc** [comment]
Happy to hear that.. 👍
