### ISSUE TITLE
Build .deb also for amd64

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#48]
In relation to https://github.com/vacuumlabs/cardano-hw-cli/issues/30 it would be nice to build also the amd64 version to not force users to enable multiarch on their operating systems before installing the package

**Comment by gacallea** [comment]
+1 please. adding 386 is not an option on docker.

**Comment by gitmachtl** [comment]
@DavidTranDucVL i changed the architecture in the deb control description from i386 to amd64, because the target is already x64. that made a deb (amd64) "version". i installed it on a blank system without any issues.

**Comment by gitmachtl** [comment]
was merged with https://github.com/vacuumlabs/cardano-hw-cli/pull/81 so you can close this issue. 😄
