### ISSUE TITLE
Transaction with metadata results in Tx serialization mismatch

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#49]
Currently it's apparently not possible to sign a transaction containing metadata. This can indeed be tricky with Trezor which expects the full metadata in order to sign given transaction, not just their hash

**Comment by refi93** [comment]
Most likely Ledger works properly, but Trezor expects the full metadata, so it may be the case we are passing the metadata hash as the metadata themselves, resulting naturally in this error

Trezor connect docs: https://github.com/trezor/connect/blob/develop/docs/methods/cardanoSignTransaction.md

**Comment by tdiesler** [comment]
Ledger doesn't work either unfortunately

```
cardano-cli transaction build-raw \
   --tx-in $TX_IN1 \
   --tx-in $TX_IN2 \
   --tx-in $TX_IN3 \
   --tx-out $REFUND_ADDR+$REFUND_LVC \
   --ttl $TTL \
   --fee $FEES_LVC \
   --json-metadata-no-schema \
   --metadata-json-file /var/cardano/local/scratch/metadata.json \
   --out-file /var/cardano/local/scratch/tx.raw

cardano-hw-cli transaction sign \
   --tx-body-file ~/cardano/scratch/tx.raw \
   --hw-signing-file ~/cardano/keys/hww/payment.hwsfile \
   --mainnet \
   --out-file ~/cardano/scratch/tx.signed

Error: Tx serialization mismatch
```

**Comment by gitmachtl** [comment]
@refi93 this issue can be closed, solved.
