### ISSUE TITLE
--hw-signing-file some explaination

### ISSUE THREAD

**Issue by QCPOLstakepool** [vacuumlabs/cardano-hw-cli#54]
This is more a question than an issue.  When using the following command it generates a signing file (`hw-signing-file`):

```
cardano-hw-cli address key-gen
  --path PATH                     Derivation path to the key we want to sign with.
  --verification-key-file FILE    Output filepath of the verification key.
  --hw-signing-file FILE          Output filepath of the hardware wallet signing file.
```

Even if I use an air-gapped machine, I don't feel safe leaving a **signing** file/key of my ledger with all my funds there. I was wondering if it's dangerous or not for my wallet if someone ever has access to this file. 

I would think it's safe, because every command using this file require the wallet to be connected and the TX has to be approved, but maybe I'm missing something (especially with a name like that). Can someone clarify?

**Comment by refi93** [comment]
Hi QCPOLstakepool, the .hwsfile do not contain the raw private key which isn't even feasible given that Ledger is designed to never export it under any circumstances

Here is an example of a hwsfile:

https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/test/integration/trezor/cli/keyFiles/payment.hwsfile

The hwsfile essentially serves as an inverse mapping from raw public keys back to derivation paths which is the way to tell Ledger to produce the corresponding private keys internally and hence the signatures needed for the given transaction.

So it's safe to store the .hwsfile even on a non-airgapped pc as long as you are not concerned about leaving traces, but your funds cannot be moved without Ledger regardless.

**Comment by QCPOLstakepool** [comment]
@refi93 Thanks, that clears my mind :) Totally makes sense!
