### ISSUE TITLE
Multiple pool registration certificates found, expected one

### ISSUE THREAD

**Issue by tdiesler** [vacuumlabs/cardano-hw-cli#55]
Could you please clarify the pool registration for multiple owners?

In the [CLI documentation](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html#build-the-transaction) we have ...

```
cardano-cli transaction build-raw \
...
--certificate-file pool-registration.cert \
--certificate-file delegation-owner1.cert
--certificate-file delegation-owner2.cert
...
--certificate-file delegation-ownerN.cert
```

but this pattern does not seem to be supported with the HW wallet. This issue is possibly a duplicate of #27, which I read carefully, but unfortunately I'm still not sure how to do this properly.

In the end I registered/updated the pool cert without providing the delegation certs for the owners. I thought this was ok because the stake addresses were registered & delegated to the pool already anyway. However, that seemed to break pool rewards.

Could you please clarify ([in the docs](https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md)) how this is supposed to work? Would it be necessary to do delegation Tx for all the owners after pool parameter have changed or is it really ok not to do that.

What I'm trying to do is this workflow as gradual transition from CLI to HW owner ...

1. Add a HW owner that does not receive pool rewards
2. Swap the owner that receives pool rewards
3. Remove the CLI owner 

Cheers

**Comment by refi93** [comment]
Hi @tdiesler thanks for raising this - indeed, hw wallets have peculiar policies for transactions involving multiple parties as there is the risk of misleading co-participants into signing parts of the transaction they think to not belong to them, given that a single witness implicitly applies to all entries within the transaction referencing it. I added a section clarifying the exact limitations into the docs:

https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md#stake-pool-registration-as-an-owner-limitations

**Comment by refi93** [comment]
and yes, given the security considerations above, delegations are to be done separately from the pool registration itself, so it's on each owner to do it on their own

**Comment by tdiesler** [comment]
Thanks for that. How does this apply to stake pool updates? Given that these are also done with `cardano-cli stake-pool registration-certificate` it can be assumed that what you say above also applies here, right?

Lets say I have a HW staking address that is already delegated to pool FOO, and I now want to make that address the owner and reward receiver for FOO. I would be doing something like this ...

```
cardano-cli stake-pool registration-certificate \
  --cold-verification-key-file /var/cardano/local/keys/pool/cold.vkey \
  --vrf-verification-key-file /var/cardano/local/keys/pool/vrf.vkey \
  --pool-pledge 10000000000 \
  --pool-cost 340000000 \
  --pool-margin 0.01 \
  --pool-reward-account-verification-key-file /var/cardano/local/keys/hww/stake.vkey \
  --pool-owner-stake-verification-key-file /var/cardano/local/keys/hww/stake.vkey \
...
```

witness that Tx and send it to the network. Would I then have to do additional steps i.e. delegating to FOO again? 
I understand that post update delegation would be necessary if `hww/stake.vkey` was not delegated at all or delegated to a different pool. Would you say that it is always good practice to post update delegate whatever you set in `pool-owner-stake-verification-key-file`?

**Comment by xdzurman** [comment]
The pool ID you delegate to - is derived from cold.vkey. That is not meant to change, so it is not necessary to re-delegate, even if other pool's parameters are changed.

Every `--pool-owner-stake-verification-key-file` must delegate to the pool in order to be counted towards the pledge amount. The `--pool-reward-account-verification-key-file` does not necessarily have to delegate to the pool - only if it is also the pool's owner. 
Delegating to the same stake pool id again is always a waste of fees. So delegate only from the owners that are not already delegating into this pool.

Your transition workflow is correct. However, note that the rewards account does not have to be one of the pool owners. For instance, you can have one reward account for multiple pools to avoid duplicate withdrawals as seen here https://adapools.org/stake/stake1uxcmc9r2t7cxs0zw8qm8ztg3twvxryzghsc8eszek6kuwms23gya4

**Comment by tdiesler** [comment]
Lovely, thanks.

**Comment by xdzurman** [comment]
I remembered though that different pool sites have different pledge counting policy, some count the pledge immediately, others with a +1/+2 epoch lag, so don't freak out and do your research which is which.
