### ISSUE TITLE
Please could you build Ubuntu version for aarch64 to work on Raspberry Pi? 

### ISSUE THREAD

**Issue by OYSTERPOOL** [vacuumlabs/cardano-hw-cli#56]
I guess the title is pretty self explanatory. I've tried building it myself and can't get it to work. There are quite a few people who would be most grateful :)

**Comment by janmazak** [comment]
It was not possible with nexe, but now we use pkg, so it will be done soon.
https://github.com/vacuumlabs/cardano-hw-cli/pull/154

Closing because the same was asked in #147
