### ISSUE TITLE
isUint64 fails for zero lovelace amounts

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#60]
Offending code: https://github.com/vacuumlabs/cardano-hw-cli/blob/5ba0cd3b8622110c842d7bafac9b3f32224fce09/src/transaction/guards.ts#L19

Context: validation of stake pool registration with zero pledge/cost fails and generally amounts of lovelace are being validated for being "uint64" but the underlying check also enforces the values to be non-zero even if that's still technically a valid uint64 - we shouldn't really restrict that though as neither the hw wallets enforce and positive values should have a separate check - perhaps we should explicitly specify the allowed range of numbers in the isValidUint64 check in the checks to keep it clear in the code.

**Comment by DavidTranDucVL** [comment]
This issue was resolved.
