### ISSUE TITLE
OperatorApp - NodeOperationalCertificateIssueCounter Index starts with 1

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#62]
```
$ cardano-hw-cli version
Cardano HW CLI Tool version 1.3.0-rc.0
Commit hash: ac794c5599ad3ab64116fba3ab621efd15d04bd8

$ cardano-hw-cli device version
Ledger app version 2.3.0
```

This is an issue related to the operatorapp version: cardano-hw-cli or the cardano-app does not like NodeOperationalCertificateIssueCounter index 0. If you loose your opcert file for whatever reason and you regenerate the opcert with the normal cardano-cli and index 0 (default, also 0 with the normal node key generation) you get an error:

`invalid issue counter`

If you modify the node counter to be 1 or higher, it works. So, this is not consistent with the normal cardano-cli.

**Comment by refi93** [comment]
another potential issue detected by @gitmachtl is that delegation transactions signed with this version of cardano-hw-cli appear to have only one witness, presumably the staking one, command used:

```
normal transaction body building including the delegation certificate:
${cardanocli} transaction build-raw ${nodeEraParam} ${txInString} --tx-out "${sendToAddr}+${lovelacesToSend}${assetsOutString}" --invalid-hereafter ${ttl} --fee ${fee} --certificate ${delegName}.deleg.cert --out-file ${txBodyFile}
transaction signing via the hw-wallet:
${cardanohwcli} transaction sign --tx-body-file ${txBodyFile} --hw-signing-file ${delegName}.staking.hwsfile --hw-signing-file ${delegName}.payment.hwsfile --change-output-key-file ${delegName}.staking.hwsfile --change-output-key-file ${delegName}.payment.hwsfile ${magicparam} --out-file ${txFile}
```

**Comment by gitmachtl** [comment]
turns out the second issue is related to a parameter order setup.

this one does **not work**, staking.hwsfile before the payment.hwsfile
``` console
${cardanohwcli} transaction sign --tx-body-file ${txBodyFile} --hw-signing-file ${delegName}.staking.hwsfile --hw-signing-file ${delegName}.payment.hwsfile --change-output-key-file ${delegName}.staking.hwsfile --change-output-key-file ${delegName}.payment.hwsfile ${magicparam} --out-file ${txFile}
```

this one **works**, payment.hwsfile before the staking.hwsfile
``` console
${cardanohwcli} transaction sign --tx-body-file ${txBodyFile} --hw-signing-file ${delegName}.payment.hwsfile --hw-signing-file ${delegName}.staking.hwsfile --change-output-key-file ${delegName}.payment.hwsfile --change-output-key-file ${delegName}.staking.hwsfile ${magicparam} --out-file ${txFile}
```

also this is the same when doing a _pool-retirement transaction_ with node keys from the hw-wallet and payment keys from the hw-wallet. you have to put the payment.hwsfile first. also as a sidenote the "retire pool id" shows only zeros instead of the actual pool id.

**Comment by refi93** [comment]
regarding the zero counter value being rejected, I found the validation of zero values in ledgerjs didn't work correctly and just rejected them all, it's fixed in https://github.com/vacuumlabs/ledgerjs-cardano-shelley/pull/99 and the fix will propagate to the final version of the cardano-hw-cli with operator app support

**Comment by DavidTranDucVL** [comment]
I believe all of these issues were resolved
