### ISSUE TITLE
Cold key generation rejected by Ledger

### ISSUE THREAD

**Issue by Urrescoding** [vacuumlabs/cardano-hw-cli#67]
Trying to create cold keys with the following command (copied from the repo):

cardano-hw-cli.exe node key-gen --path 1853H/1815H/0H/0H --hw-signing-file cold.hwsfile --cold-verification-key-file cold.vkey --operational-certificate-issue-counter-file cold.counter

Returns the following error:
Error: Ledger device: Action rejected by Ledger's security policy

**Comment by gitmachtl** [comment]
This is in DEV-Mode right now, you would need too flash the ledger with a dev ledger-app version for that

**Comment by Urrescoding** [comment]
Thanks, so I guess it's gonna take some time until it works with the standard ledger app

**Comment by gitmachtl** [comment]
yes, correct.

**Comment by Urrescoding** [comment]
And is there any tentative release date for a compatible ledger app? Just want to know if it is going to be within the next release or later than that

**Comment by gitmachtl** [comment]
Not in the next release, the next one is focused on the Catalyst-Voting integration. But in the one after that 😄

**Comment by Urrescoding** [comment]
ok, thanks for your answer! I close the issue
