### ISSUE TITLE
Error when signing witness with delegation certificates

### ISSUE THREAD

**Issue by Urrescoding** [vacuumlabs/cardano-hw-cli#69]
I am using the following command to build the transaction for the pool registration:

_cardano-cli transaction build-raw \
    ${tx_in} \
    --tx-out $(cat operator_payment.addr)+${txOut} \
    --invalid-hereafter $(( ${currentSlot} + 10000)) \
    --fee ${fee} \
    --certificate-file pool.cert \
    --certificate-file deleg_1.cert \
    --certificate-file deleg_2.cert \
    --out-file tx.raw_

However, when trying to create the witnesses with cardano-hw-cli (with hwsfile for both delegation certs), I get the following error:
**Error: Multiple pool registration certificates found, expected one**

I just read that there only has to be one certificate in the transaction (the pool.cert). However, I dont understand how I am supposed to add the delegation certificates for the owners, if I cannot sign them with the hardware wallets.

**Comment by gitmachtl** [comment]
Its not allowed to also pool delegation certificated into a pool-registration that involves a hw-wallet. Thats for security reasons. So, you have to leave the delegations out of the transaction and do it afterwards in a 2nd one.

**Comment by Urrescoding** [comment]
Ok, understood, thank you
