### ISSUE TITLE
Feature request: bash completion

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#7]
For a better user experience, it would be nice to have bash completion, so the full command is auto-completed by pressing <tab> after typing the first few letters. Feature request by @disassembler

npm packages that may be helpful for achieving this are for example yargs or tabtab : https://stackoverflow.com/questions/19990639/how-to-add-tab-completion-to-a-nodejs-cli-app

**Comment by DavidTranDucVL** [comment]
Done in https://github.com/vacuumlabs/cardano-hw-cli/pull/11
