### ISSUE TITLE
Possibly inconsistent owners given as path validation between Ledger and Trezor

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#71]
Trezor provider apparently checks for both the case when there are no owners given as path and when there are multiple:

https://github.com/vacuumlabs/cardano-hw-cli/blob/37ce69eec81bfdb0f463eda630391e2132e17f63/src/crypto-providers/trezorCryptoProvider.ts#L253-L254

However Ledger provider seems to check only the case when multiple owners are supplied
https://github.com/vacuumlabs/cardano-hw-cli/blob/37ce69eec81bfdb0f463eda630391e2132e17f63/src/crypto-providers/ledgerCryptoProvider.ts#L252

This is probably due to pool operator support on Ledger but when signing as an owner this may be the cause of a bug report by disasm related to an inconsistent error message when the certificate allegedly didn't match the owner key supplied:

> An SPO mentioned they were getting an error on their ledger device when trying to witness a pool tx and gets the error there should be exactly 1 owner given by path in a registration certificate.

**Comment by janmazak** [comment]
Yes, Ledger expects exactly 1 owner, and it would be much better if hw-cli return an error mentioning signing files (instead of the underlying ledgerjs error). @KubqoA have you done anything about it yet?

**Comment by davidmisiak** [comment]
I've fixed it as a part of the Alonzo PR. https://github.com/vacuumlabs/cardano-hw-cli/pull/112/commits/463ea475fa8f563ba78b01f145ec5f24fff32d87

**Comment by gitmachtl** [comment]
What does it exactly mean "1 owner"? We have multiowner pools on Cardano with multiple HW-Wallets registered as Owners. Or are we talking other "owners" here?
