### ISSUE TITLE
can't use node argument

### ISSUE THREAD

**Issue by Mina-Farahat** [vacuumlabs/cardano-hw-cli#74]
I'm using macOS build version 1.2.0
When I try to generate node key , I get the following message cardano-hw-cli: error: invalid choice: 'node' (choose from 'version', 'device', 'address', 'key', 'transaction') although on the examples it shows that node is supported .

Using Ledger nano s , Cardano app 2.3.2

**Comment by gitmachtl** [comment]
https://github.com/vacuumlabs/cardano-hw-cli/issues/67

There is currently no hw-cli-version available that supports it, and even so, there is no public cardano-app available that supports it right now. Its in dev state...

**Comment by Mina-Farahat** [comment]
Thanks a lot for the support , is there an estimated data when the ledger Cardano app which support such function will be released ?

**Comment by gitmachtl** [comment]
I guess within the next weeks.

**Comment by Mina-Farahat** [comment]
Thanks a lot :)

**Comment by Mina-Farahat** [comment]
Is there a repo to follow the activity of developing Ledger Cardano app ?
