### ISSUE TITLE
cardano-cli 1.27.0 transactions fail

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#75]
cardano-cli 1.27.0 apparently introduced an additional item in the tx body to be signed - an empty list (script witnesses) before the metadata. This results in cardano-hw-cli picking up that second list item as metadata which then results in a malformed transaction

Here is the cardano-node PR with the cardano-cli breaking change (probably): https://github.com/input-output-hk/cardano-node/pull/2547

So now the second item of the list (which the unsigned tx body file encodes) is not the metadata but list of scripts. However, cardano-hw-cli incorrectly takes the second item (the empty list) and considers it metadata which then results in an invalid signed transaction being assembled which has an empty list instead of the actual metadata/auxiliary data being present in the transaction

Proposed fix:
* check if the tx body list to be parsed has three items or two - if it has two, fall back to old behavior, if three, enforce the second item to be an empty list (as we don't support scripts yet) and take the third item as metadata

Examples of tx bodies produced by cardano-cli 1.27.0:

```json
{
    "type": "TxBodyMary",
    "description": "",
    "cborHex": "83a400818258202060c923723d7d58cd11f22734348aa7e1b04dad5d9133082531587d16d6fb8401018282581d6052e63f22c5107ed776b70f7b92248b02552fd08f3e747bc7450994411a009896808258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf1b0000048c5b396397021a0002a961031a01a192e49ffff6"
}
```
- notice the list has three items and the null metadata is last and an empty list (no scripts) before it

tx body produced by cardano-cli 1.26.2:

```json
{
    "type": "TxBodyMary",
    "description": "",
    "cborHex": "82a400818258201e95b2d4c412a18037a62af415da05db317cddc7c91190df731ad1cf771e709e01018282581d6052e63f22c5107ed776b70f7b92248b02552fd08f3e747bc7450994411a00e4e1c08258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf1b0000048c5cbc2e99021a0002a961031a01a18ebef6"
}
```
- notice the list has only two items

**Comment by DavidTranDucVL** [comment]
Is there a cddl for new format? Can't find it.

**Comment by gitmachtl** [comment]
> Is there a cddl for new format? Can't find it.

https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl

**Comment by DavidTranDucVL** [comment]
Resolved in https://github.com/vacuumlabs/cardano-hw-cli/pull/78
