### ISSUE TITLE
cardano-hw-cli seems not working anymore with the latest cardano app on Ledger

### ISSUE THREAD

**Issue by snajjar** [vacuumlabs/cardano-hw-cli#79]
I updated all applications in my Ledger, but now cardano-cli consistently show me the following error message whenever I try to sign a transaction : 

    Error: Error occured while trying to find hw transport, make sure Ledger or Trezor is connected to you computer

This worked before, as I successfully added my Ledger adress as the owner of my stakepool.
I'm now stuck with a pledge I can't meet anymore... :/

Please help

**Comment by gitmachtl** [comment]
cardano-hw-cli 1.2.0 works normally with cardano-ledger-app 2.3.2, please use cardano-node 1.26.2 with that combination for now. but your error code looks like a rights issue to me. have you changed the machine or not set the required hw-rules so the non-root user can access the ledger hardware-wallet?

**Comment by snajjar** [comment]
Hello, 

Thank you for the quick response!
lsusb was indeed showing me vendor 2c97, no problem on that end.

I finally found the issue : I move the cardano-hw-cli binary file to some other location, and it seems that it doesn't work without the rest of the files (package.json and .node files) properly placed in the same path (but doesn't show a proper error message in that case). That was dumb, I admit.

Thank you for the information.

> you have always full access to your funds on your ledger via a wallet like adalite/yoroi/daedalus.

Yeah, but sometime you just need to lower your pledge... Since my ledger is now a pool owner, it's critical that I can use cardano-hw-cli when doing such operations.

**Comment by gitmachtl** [comment]
Ok, so i guess the issue can be closed?

**Comment by snajjar** [comment]
I'm getting a different error now when trying to sign the transaction : 
"Error: invalid uint32 value".

At first the ledger pops a "start new transaction ?" message, and when I confirm,  the cardano app become frozen with a spinner on the ledger device, I can only power it off to unfreeze it. I did revert to cardano-node 1.26.2 as you suggested. Any idea about that?

**Comment by gitmachtl** [comment]
Can you please write all your versions and revisions, and, what type of transaction are your trying to do?

**Comment by snajjar** [comment]
Of course.

I'm using:
- Linux Kernel 5.11.16 (ArchLinux)
- cardano-hw-cli v1.2.0
- cardano-node v1.26.2
- node v13.14.0

I'm trying to change my pool registration certificate, to update my pledge. The pool now have 2 owners, my previous hot wallet, and my hardware wallet. I'm trying to craft a transaction and sign it with a procedure I fully described [here](https://github.com/snajjar/cardano-shell-docker#step-3-create-a-transaction-and-use-cardano-hw-cli-to-sign-it).

Is there any other info that could be helpfull?

**Comment by gitmachtl** [comment]
and your cardano ledger app is on 2.3.2 ?

is one of your pool parameters zero? poolFee or pledge?

**Comment by snajjar** [comment]
Yes, cardano ledger was on 2.3.2

Exactly, pledge was 10k ada and pool fee 340 ada, pool margin 1%. No parameter set to 0.

**Comment by gitmachtl** [comment]
Thats strange. I have written all the cli commands into a handful of scripts, i have not seen an error like that before.
I would say, try it again with the new cardano-hw-cli that is 1.27.0 compatible that will be released ASAP.

**Comment by snajjar** [comment]
All right, will do that!

**Comment by snajjar** [comment]
I've compiled the lastest cardano-hw-cli from sources to try it out.

Trying to sign the same transaction (from cardano-node 1.26.2) now issue the following error:

    Error: invalid input utxo index

Is the new version not backward-compatible with cardano-node 1.26.2? Should I try to use it with cardano-node 1.27.0?

**Comment by gitmachtl** [comment]
maybe the error messages are better now, are you sure your inputs are correct? are you trying to just sign the made tx-body? maybe there was a transaction on that address in the meantime?

the new version is backwards-compatible with 1.26.2

**Comment by snajjar** [comment]
Yes, i'm still trying to sign the same transaction (but I can create a new one, since the TTL must be dead now).
No transactions in the meantime.

I'll try to generate a new transaction and sign that one with this new branch, from a cardano-node 1.27.0, i'll keep you up to date.

**Comment by gitmachtl** [comment]
I think this issue can be closed now

**Comment by gitmachtl** [comment]
@refi93 this issue can be closed, solved.
