### ISSUE TITLE
Errors in manual

### ISSUE THREAD

**Issue by asbator** [vacuumlabs/cardano-hw-cli#84]
https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md

In 3rd command there is path error. But it doesnt work either with 1852H/1815H/0H/2/0 nor 1852H/1815H/0H/0/0.
I get error: invalid node key-gen inputs.

Also are you sure that reward address is made with command "stake-address build"?

**Comment by gitmachtl** [comment]
The current Cardano-Ledger-App 2.3.2 does not support Pool Cold Keys yet.

**Comment by asbator** [comment]
How to solve that problem?

**Comment by gitmachtl** [comment]
By waiting for Ledger to approve the current PR (https://github.com/LedgerHQ/app-cardano/pull/11) 😄

**Comment by asbator** [comment]
Error: Unexpected payment hardware signing file with pool registration certificate found
and
Error: Multiple pool registration certificates found, expected one
while trying to creating witnesses for pool registration are same problem?

**Comment by asbator** [comment]
it signs with cardano-cli and skey

**Comment by asbator** [comment]
at last something meaningful Error : invalid pool reward account type for legacy Ledger version

**Comment by gitmachtl** [comment]
Please use cardano-hw-cli release 1.5.0, version 1.6.0 is a pre-release now that is only compatible with the upcoming cardano-ledger-app 2.4.0 -> https://github.com/vacuumlabs/cardano-hw-cli/issues/83

**Comment by asbator** [comment]
it worked with owner-stake.hwsfile.

but trying to witness with operator-payment.hwsfile i still get:
Unexpected payment hardware signing file with pool registration certificate found

"Also note that the reward address does not have to be witnessed when registering the stake pool, so you don't have to provide the corresponding staking signing key when registering the stake pool unless it's bound to an owner as well." - means that i dont have to witness with oprator-stake.hwsfile , but i still have to witness with operator-payment.hwsfile  - right?

**Comment by gitmachtl** [comment]
Its not possible to pay with a hardware wallet for a pool registration, thats for security reasons. You have to use a small CLI-Wallet for that.

**Comment by asbator** [comment]
i dont understand. You've made manual how to make pool registration with Ledger, but it cant be done "for security reasons".

**Comment by gitmachtl** [comment]
You can have the owner-pledge funds and rewards on a Ledger. You can also soon have the pool-node cold keys on the hw-wallet. But there are security limitation on what you can do with a HW-Wallet. One of them is, that you can sign the witness for a pool-registration/reregistration. But you're not able to pay with it from a HW-Wallet. Thats the reason an SPO should always have a small cli wallet just for the "daily" pool operation. Other limititation in the other direction is for example that you have to pay with the hw-wallet to register the stake-key of the hw-wallet itself. So in this case, its needed to use the HW-Wallet. But a Pool-Registration is too complex, and the attached certificates could lead to a Security issue. Thats the reason the decision was made that you can't pay for a pool-registration with a HW-Wallet. 

You can find a little list here: https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#limitations-to-the-pooloperation-when-using-hardware-wallets

Open up the Limitation sheet...

**Comment by asbator** [comment]
thx for good explanation.
near the end of manual is "We use Ledger to create all witnesses".
i see that coincashew is the only really working manual in almost every aspect (just mistake with not needed deleg.cert).
for some reason this community lacks good thorough documentation. or maybe im just to stupid.
