### ISSUE TITLE
Cannot create separate witness for transaction other than pool registration

### ISSUE THREAD

**Issue by rynz** [vacuumlabs/cardano-hw-cli#88]
I am attempting to create a multi-wallet transaction and would like to pay the fee with my hardware wallet. I've created multi-wallet transactions before, however when I attempt:
```
$ cardano-hw-cli transaction witness \
  --tx-body-file tmp/tx.raw \
  --hw-signing-file payment.hwsfile \
  --mainnet \
  --out-file tmp/payment.witness
```
I get:
```
Error: Cannot create separate witness for the transaction other than pool registration, use "sign" subcommand instead
```
https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/src/crypto-providers/util.ts#L299-L317
Is there a reason for this limitation?

**Comment by davidmisiak** [comment]
@rynz Sorry for the delay, this should be fixed in the December [v1.9.1 release](https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.9.1).
