### ISSUE TITLE
Alonzo-era tx bodies not working properly

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/cardano-hw-cli#89]
@gitmachtl while testing the cli noticed that it doesn't support alonzo-era tx bodies:

```
{
    "type": "TxBodyAlonzo",
    "description": "",
    "cborHex": "85a60081825820d792c4a513a6a8b319d32ce204b6cde6c98e63ae5fb2efc9f228bfb52d5ef9a9000d80018282581d6088ff402b0522f27649ac742238c697c579beeb344eb723099d1f16ce1a000f424082581d6088ff402b0522f27649ac742238c697c579beeb344eb723099d1f16ce1b00001fd36ef168d0021a0002a8b1031a002f95990e809fff8080f6"
}
```

Equivalent Mary-era transaction:
```
{
    "type": "TxBodyMary",
    "description": "",
    "cborHex": "83a40081825820fb196c391c4f31da1da12c480a1c5077ed30286468605c3489a6977588a7cc6900018282581d6088ff402b0522f27649ac742238c697c579beeb344eb723099d1f16ce1a000f424082581d6088ff402b0522f27649ac742238c697c579beeb344eb723099d1f16ce1b00001fd36eeebb23021a0002a8b1031a002f95f19ffff6"
}
```

Given that there are new fields (13, 14) it seems this depends on Ledger/Trezor being updated, what's a bit confusing though Is that the "13" key in the alonzo-era tx body seems to be out of order

Alonzo-era CDDL: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/alonzo/test/cddl-files/alonzo.cddl

**Comment by gabrielKerekes** [comment]
Hi @gitmachtl how was the Alonzo tx body created please? If through cardano-cli which version? To me it doesn't seem to be inline with the Alonzo CDDL because there's 5 transaction elements although there should just be 3, so it's suspicious. I'd like to understand this better before moving forward.

**Comment by gitmachtl** [comment]
@gabrielKerekes sure, the transaction was build with the current latest cardano-cli version for the alonzo testnet -> cardano-node -> tags/alonzo-blue2.0

yes the additional fields in the alonzo tx body are script witnesses, plutus stuff ...

**Comment by snic-csp** [comment]
Are there any updates for this? Thanks

**Comment by gabrielKerekes** [comment]
Hi all, we are currently finalising Alonzo/Plutus updates for HW wallets and after that, we will move on to HW CLI. We are also waiting for an update to cardano-cli regarding its transaction formats which should also be out soon.

**Comment by ahjumma** [comment]
@gabrielKerekes 
Thanks for letting us know!

**Comment by davidmisiak** [comment]
Here is the v1.10.0 release that enables Alonzo-era txs: https://github.com/vacuumlabs/cardano-hw-cli/releases/tag/v1.10.0
We apologize for the delay. Should there be any trouble, feel free to open an issue.
