### ISSUE TITLE
InvalidWitnessesUTXOW using Ledger S

### ISSUE THREAD

**Issue by nycksw** [vacuumlabs/cardano-hw-cli#92]
Greetings, folks! I run a pool that's already registered, its pledge secured via a Ledger S hardware wallet, thanks to your excellent `cardano-hw-cli` tool.

However, I've been having a problem _updating_ the registration. It now fails with an `InvalidWitnessesUTXOW` error. I've checked each key file and command dozes of times, and at this point I'm concerned there might be a bug with the Ledger interaction. I would love if someone could take a look and let me know what you think. 🙏

<hr>

[ On COLD machine: ]

cardano-cli stake-pool registration-certificate --cold-verification-key-file node.vkey --vrf-verification-key-file vrf.vkey --pool-pledge [...] --pool-cost 340000000 --pool-margin 0 --pool-reward-account-verification-key-file hw-stake.vkey --pool-owner-stake-verification-key-file stake.vkey --pool-owner-stake-verification-key-file hw-stake.vkey --single-host-pool-relay [relay1] --pool-relay-port 6000 --single-host-pool-relay [relay2] --pool-relay-port 6000 --mainnet --metadata-url http://[...] --metadata-hash 6624[...]fc60 --out-file pool.cert

[ Copied pool.cert to HOT machine. ]

[ On HOT machine: ]

cardano-cli transaction build-raw --tx-in 9a00[...]a100#0 --tx-out addr1q8d[...]7rke+1023022675 --invalid-hereafter 36378857 --fee 0 --certificate-file pool.cert --out-file /tmp/tmp.wIn87F96O4

cardano-cli transaction calculate-min-fee --tx-body-file /tmp/tmp.wIn87F96O4 --tx-in-count 1 --tx-out-count 1 --mainnet --witness-count 4 --byron-witness-count 0 --protocol-params-file params.json

cardano-cli transaction build-raw --tx-in 9a00[...]a100#0 --tx-out addr1q8d[...]7rke+1022820214 --invalid-hereafter 36378857 --fee 202461 --certificate-file pool.cert --out-file tx-pool.raw

[ Copied tx-pool.raw to COLD machine. ]

[ On COLD machine: ]

cardano-cli transaction witness --tx-body-file tx-pool.raw --signing-key-file node.skey --out-file node.witness --mainnet

cardano-cli transaction witness --tx-body-file tx-pool.raw --signing-key-file stake.skey --out-file stake.witness --mainnet

cardano-cli transaction witness --tx-body-file tx-pool.raw --signing-key-file payment.skey --out-file payment.witness --mainnet

[ Unlocked ledger. ]

cardano-hw-cli transaction witness --tx-body-file tx-pool.raw --hw-signing-file hw-stake.hwsfile --out-file tx.hw-witness --mainnet

cardano-cli transaction assemble --tx-body-file tx-pool.raw --witness-file node.witness --witness-file stake.witness --witness-file payment.witness --witness-file hw-stake.witness --out-file tx-pool.multisign

[ Copied tx-pool.multisign to HOT machine. ]

[ On HOT machine: ]

cardano-cli transaction submit --tx-file tx-pool.multisign --mainnet

**Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey "e!) \247^PS4\235\163\166\\`\184\200\217\&0/i\248u\223\226\175\227\155\236\199\233_\204"))])])**

**Comment by nycksw** [comment]
Also, this isn't shown above, but I've re-exported my hardware keys to verify they're identical to the ones used in the output above. I used the following command to extract the keys:

`cardano-hw-cli address key-gen --path 1852H/1815H/0H/2/0 --verification-key-file hw-stake.vkey --hw-signing-file hw-stake.hwsfile`

Again, I _was_ able to register this pool once using the process above, but updating the registration is failing.

**Comment by gitmachtl** [comment]
what cardano-node/cli version are you using and what cardano-app version are you using?

**Comment by gitmachtl** [comment]
i retried it myself again without any issue, i set up the same config here, with a cli stake owner and a hw-owner (nano s), rewards going also to the hw-wallet like:

```json
{
  "poolName": "alonzopool/alonzopool",
  "poolOwner": [
    {
      "ownerName": "alonzopool/owner",
      "ownerWitness": "local"
    },
    {
      "ownerName": "alonzopool/hw-owner",
      "ownerWitness": "local"
    }
  ],
  "poolRewards": "alonzopool/hw-owner",
```

cardano-hw-cli 1.6.2
cardano-app 2.4.1

**Comment by nycksw** [comment]
Thanks for your time on this!

> what cardano-node/cli version are you using and what cardano-app version are you using?

cardano-hw-cli: 1.6.2
cardano-app (ledger): 2.4.1
cardano-cli: 1.27.0 (both nodes)

> and, you cli stake key is registered on the blockchain?

Can't we infer this is true since the pool is already registered using the same keys? (How can I double-check this for a given key?)

**Comment by gitmachtl** [comment]
You can check the rewards of that key and see if there is a [] in the json output instead of null. Or you can simply check the stakeadress via cardanoscan.io for example. The transaction would fail if your cli stake key or your hw-stake key is not registered before doing the transaction.
You have done this exact operation before and now only changing some pool parameters?

**Comment by nycksw** [comment]
AFAICT, the stake address looks OK:

cardano-cli query stake-address-info --address $(cat stake.addr) --mainnet
[
    {
        "address": "stake1uyxps8qd0l5yp99680d6gpxgk3lasys8c240qwcfm8wqpmcxaxgkn",
        "rewardAccountBalance": 0,
        "delegation": "pool14ecpt42vvd8eytuqpkvqq55u83dqqu2g4wwhj2kylue6utptm63"
    }
]

And: [https://cardanoscan.io/stakekey/stake1uyxps8qd0l5yp99680d6gpxgk3lasys8c240qwcfm8wqpmcxaxgkn](https://cardanoscan.io/stakekey/stake1uyxps8qd0l5yp99680d6gpxgk3lasys8c240qwcfm8wqpmcxaxgkn)

> You have done this exact operation before and now only changing some pool parameters?

Correct, just adding a relay and updating the metadata hash for the pool cert. Everything else (accounts, keys, etc.) is identical to the previous (successful) registration.

**Comment by nycksw** [comment]
Here's the previous registration tx: https://cardanoscan.io/transaction/1eda085851af5c85971db9511c3b5f995676334a08866c416dbe8fa485e1377f?tab=poolcertificates

**Comment by gitmachtl** [comment]
your payment wallet is not your hw-wallet, right?

**Comment by nycksw** [comment]
> your payment wallet is not your hw-wallet, right?

Correct, the payment address is the smaller, non-hardware wallet.

**Comment by gitmachtl** [comment]
hmm... a bit strange. can't replicate the issue here. if you like you could try to import your pool setting into my operator scripts, there is a specific script to get the data from the blockchain. the hw-owner can be added later by editing. its also possible to work in an online/offline workflow. maybe give it a try and see if the error is the same on your side?

**Comment by nycksw** [comment]
These, right?: https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet ... I'll check them out, thanks. And thanks again for taking a look at this!

Something else you might know... in the error message, it ends with a backslash-delimited string of numbers:

> Command failed: transaction submit Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey "e!) \247^PS4\235\163\166\`\184\200\217&0/i\248u\223\226\175\227\155\236\199\233_\204"))])])`

Can you tell what that string is referring to? I was hoping it might be a clue to the specific keypair that's failing.

**Comment by gitmachtl** [comment]
> These, right?: https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet ... I'll check them out, thanks. And thanks again for taking a look at this!
correct

> Can you tell what that string is referring to? I was hoping it might be a clue to the specific keypair that's failing.
it is a bit of a strange output with that kind of backslash-delimited numbers and chars like `. maybe there is an issue with the copying from the offline/online/offline process at your side. did you make a file copy or a copy&paste via some kind of editor? look into each .vkey file if you see any strange charset or so. but all is going well until the sending point, so it is strange.

**Comment by nycksw** [comment]
> did you make a file copy or a copy&paste via some kind of editor? look into each .vkey file if you see any strange charset or so. but all is going well until the sending point, so it is strange

I'm using a USB stick to transfer files, and I'm running md5sum on the files on each side to ensure they're identical.

> are you 100% sure you use the right hw-wallet?

Yes, I even re-extracted the keys from that device and diffed them against the ones I'm using to be sure. (But it's clear from the balance, anyway.)

I also sent a small test-transaction via the CLI from each wallet (both the payment wallet and the hardware wallet) to ensure I've got the right keys for each. Those tx's succeeded, but the re-registration still fails. 😫

**Comment by nycksw** [comment]
Plot thickens...

I decided to try re-registering the pool _without_ the hardware keys (I lowered the pledge accordingly, but everything else the same) and it worked just fine. Then I tried again _with_ the hardware keys (exactly as in my initial bug report) and got the same error as before (`InvalidWitnessesUTXOW`).

I'm going to try doing this again with a different Ledger Nano S device. I can't imagine that would make a difference, but I'd like to rule it out.

**Comment by nycksw** [comment]
I moved the pledge to new ledger and tried re-registering again, but got similar error:

> cardano-cli transaction submit --tx-file tx-pool.multisign --mainnet
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey "e!) \247^PS4\235\163\166\\`\184\200\217\&0/i\248u\223\226\175\227\155\236\199\233_\204"))]),UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash "3ba58[...redacted for privacy...]17a7"])))])

Interestingly, the end of that error had a friendlier address string this time, so I plugged it into Cardanoscan.io and it is the stake key for the new Ledger I switched to. That's really confusing. I'm _definitely_ using the hw-stake.hwsfile as outputted via `cardano-hw-cli address key-gen` from that device to sign the Tx. 🤔

**Comment by nycksw** [comment]
Oof, problem solved. I was using all the right keys but one of my signing commands had a typo in it, and that resulted in using an old witness file. So, PEBKAC! 😩 Thanks for helping me work through this.

**Comment by nycksw** [comment]
If anyone is curious about the typo, here it is, as written in the original bug:

> cardano-hw-cli transaction witness --tx-body-file tx-pool.raw --hw-signing-file hw-stake.hwsfile --out-file **tx.hw-witness** --mainnet

> cardano-cli transaction assemble --tx-body-file tx-pool.raw --witness-file node.witness --witness-file stake.witness --witness-file payment.witness --witness-file **hw-stake.witness** --out-file tx-pool.multisign

Note that the first command writes out to `tx.hw-witness`, and the second reads from `hw-stake.witness`.  Everything worked fine up until submitting the tx, since a previous invocation had written to `hw-stake.witness`, so it existed.  So, of course, the tx failed because the witness file was from a previous tx.  I should have tried your script as soon as you mentioned it, Martin! (Although, it would have worked and I would have had no idea why... hah!)

**Comment by gitmachtl** [comment]
Glad you found it 😃
